export default {
  slogin: "longhai2210",
  id: 36153109,
  node_id: "MDQ6VXNlcjM2MTUzMTA5",
  avatar_url: "https://avatars0.githubusercontent.com/u/36153109?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/longhai2210",
  html_url: "https://github.com/longhai2210",
  followers_url: "https://api.github.com/users/longhai2210/followers",
  following_url: "https://api.github.com/users/longhai2210/following{/other_user}",
  gists_url: "https://api.github.com/users/longhai2210/gists{/gist_id}",
  starred_url: "https://api.github.com/users/longhai2210/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/longhai2210/subscriptions",
  organizations_url: "https://api.github.com/users/longhai2210/orgs",
  repos_url: "https://api.github.com/users/longhai2210/repos",
  events_url: "https://api.github.com/users/longhai2210/events{/privacy}",
  received_events_url: "https://api.github.com/users/longhai2210/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "random user",
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-02-05T09:16:02Z",
  updated_at: "2020-08-05T04:32:07Z",
};
